import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Home/NavBar'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
